project:
  type: book
  output-dir: chapters

book:
  title: "Data Driven Process Management"
  author: "Witek ten Hove"
  date: "10/2/2023"
  language: "nl"
  chapters:
    - index.qmd
    - intro.qmd
    - culture.qmd
    - sourcing.qmd
    - capabilities.qmd
    - decisions.qmd
    - value.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual
lang: "nl"

